package com.dereliktt.EpicArmor.models;

import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelEpicArmorCommander extends ModelBiped
	{
	  //fields
		public Boolean hasCloak = true;
	
	    ModelRenderer head;
	    ModelRenderer HelmForeHead;
	    ModelRenderer LeftHelmForeHead;
	    ModelRenderer RightHelmForeHead;
	    ModelRenderer HelmNosePlate;
	    ModelRenderer HelmRidgeCenter;
	    ModelRenderer HelmRidgeCenter2;
	    ModelRenderer HelmRidgeCenter3;
	    ModelRenderer HelmRidgeCenter4;
	    ModelRenderer HelmRidgeCenter5;
	    ModelRenderer HelmRidgeCenter6;
	    ModelRenderer HelmRidgeCenter7;
	    ModelRenderer HelmRidgeCenter8;
	    ModelRenderer HelmRidgeCenter9;
	    ModelRenderer HelmRidgePlateBack;
	    ModelRenderer HelmRidgePlateCenter;
	    ModelRenderer HelmRidgePlateFront;
	    ModelRenderer LeftHelmTop;
	    ModelRenderer RightHelmTop;
	    ModelRenderer HelmBackPlate;
	    ModelRenderer LeftHelmForeheadPlate;
	    ModelRenderer LeftHelmSidePlate;
	    ModelRenderer RightHelmForeheadPlate;
	    ModelRenderer RightHelmSidePlate;
	    ModelRenderer RightHelmSideFacePlate;
	    ModelRenderer RightHelmFacePlate;
	    ModelRenderer LeftHelmSideFacePlate;
	    ModelRenderer LeftHelmFacePlate;
	    ModelRenderer body;
	    ModelRenderer ChestPlate;
	    ModelRenderer ChestPlate2;
	    ModelRenderer ChestPlate3;
	    ModelRenderer ChestPlate4;
	    ModelRenderer Girdle;
	    ModelRenderer BackPlate3;
	    ModelRenderer Cloak;
	    ModelRenderer Buckle;
	    ModelRenderer rightarm;
	    ModelRenderer RightShoulderBase;
	    ModelRenderer RightShoulderPlate;
	    ModelRenderer LeftShoulderTopPlate;
	    ModelRenderer leftarm;
	    ModelRenderer LeftShoulderBase;
	    ModelRenderer RightShoulderBase2;
	    ModelRenderer LeftShoulderBase2;
	    ModelRenderer RightBottomShoulderPlate;
	    ModelRenderer LeftBottomShoulderPlate;
	    ModelRenderer LeftShoulderPlate;
	    ModelRenderer LeftShoulderMainPlate;
	    ModelRenderer RightShoulderTopPlate;
	    ModelRenderer RightShoulderMainPlate;
	    ModelRenderer RightShoulderDeco;
	    ModelRenderer LeftShoulderDeco;
	    ModelRenderer leftleg;
	    ModelRenderer rightleg;
	    ModelRenderer LeftThighPlate;
	    ModelRenderer LeftThighPlate2;
	    ModelRenderer RightThighPlate;
	    ModelRenderer RightThighPlate2;
	    ModelRenderer RightThighPlate3;
	    ModelRenderer LeftThighPlate3;
	    ModelRenderer RightBoot;
	    ModelRenderer LeftBoot;
	  
	  public ModelEpicArmorCommander(float expand)
	  {
		  super(expand, 0.1f, 128, 64);
	      //Head
		  
	      head = new ModelRenderer(this, 0, 0);
	      head.addBox(-4F, -8F, -4F, 8, 8, 8);
	      head.setRotationPoint(0F, 0F, 0F);
	      head.setTextureSize(64, 32);
	      head.mirror = true;
	      setRotation(head, 0F, 0F, 0F);
	      HelmForeHead = new ModelRenderer(this, 82, 10);
	      HelmForeHead.addBox(-0.5F, -8F, -5.033333F, 1, 3, 1, expand/3);
	      HelmForeHead.setRotationPoint(0F, 0F, 0F);
	      HelmForeHead.setTextureSize(64, 32);
	      HelmForeHead.mirror = true;
	      setRotation(HelmForeHead, 0F, 0F, 0F);
	      LeftHelmForeHead = new ModelRenderer(this, 72, 10);
	      LeftHelmForeHead.addBox(0F, -8F, -5F, 4, 3, 1, expand/3);
	      LeftHelmForeHead.setRotationPoint(0F, 0F, 0F);
	      LeftHelmForeHead.setTextureSize(64, 32);
	      LeftHelmForeHead.mirror = true;
	      setRotation(LeftHelmForeHead, 0F, -0.1047198F, 0F);
	      RightHelmForeHead = new ModelRenderer(this, 72, 10);
	      RightHelmForeHead.addBox(-4F, -8F, -5F, 4, 3, 1, expand/3);
	      RightHelmForeHead.setRotationPoint(0F, 0F, 0F);
	      RightHelmForeHead.setTextureSize(64, 32);
	      RightHelmForeHead.mirror = true;
	      setRotation(RightHelmForeHead, 0F, 0.1047198F, 0F);
	      RightHelmForeHead.mirror = false;
	      HelmNosePlate = new ModelRenderer(this, 86, 10);
	      HelmNosePlate.addBox(-1F, -4.933333F, -5.3F, 2, 2, 1, expand/3);
	      HelmNosePlate.setRotationPoint(0F, 0F, 0F);
	      HelmNosePlate.setTextureSize(64, 32);
	      HelmNosePlate.mirror = true;
	      setRotation(HelmNosePlate, -0.0698132F, 0F, 0F);
	      HelmRidgeCenter = new ModelRenderer(this, 32, 0);
	      HelmRidgeCenter.addBox(-0.501F, -14.2F, -1F, 1, 6, 2, expand/3);
	      HelmRidgeCenter.setRotationPoint(0F, 0F, 0F);
	      HelmRidgeCenter.setTextureSize(64, 32);
	      HelmRidgeCenter.mirror = true;
	      setRotation(HelmRidgeCenter, -0.0872665F, 0F, 0F);
	      HelmRidgeCenter2 = new ModelRenderer(this, 32, 0);
	      HelmRidgeCenter2.addBox(-0.499F, -14.2F, -1F, 1, 6, 2, expand/3);
	      HelmRidgeCenter2.setRotationPoint(0F, 0F, 0F);
	      HelmRidgeCenter2.setTextureSize(64, 32);
	      HelmRidgeCenter2.mirror = true;
	      setRotation(HelmRidgeCenter2, 0.0523599F, 0F, 0F);
	      HelmRidgeCenter3 = new ModelRenderer(this, 32, 0);
	      HelmRidgeCenter3.addBox(-0.501F, -14.2F, -1F, 1, 5, 2, expand/3);
	      HelmRidgeCenter3.setRotationPoint(0F, 0F, 0F);
	      HelmRidgeCenter3.setTextureSize(64, 32);
	      HelmRidgeCenter3.mirror = true;
	      setRotation(HelmRidgeCenter3, 0.4712389F, 0F, 0F);
	      HelmRidgeCenter4 = new ModelRenderer(this, 32, 0);
	      HelmRidgeCenter4.addBox(-0.499F, -14.2F, -1F, 1, 5, 2, expand/3);
	      HelmRidgeCenter4.setRotationPoint(0F, 0F, 0F);
	      HelmRidgeCenter4.setTextureSize(64, 32);
	      HelmRidgeCenter4.mirror = true;
	      setRotation(HelmRidgeCenter4, -0.5061455F, 0F, 0F);
	      HelmRidgeCenter5 = new ModelRenderer(this, 32, 0);
	      HelmRidgeCenter5.addBox(-0.501F, -14.2F, -1F, 1, 6, 2, expand/3);
	      HelmRidgeCenter5.setRotationPoint(0F, 0F, 0F);
	      HelmRidgeCenter5.setTextureSize(64, 32);
	      HelmRidgeCenter5.mirror = true;
	      setRotation(HelmRidgeCenter5, 0.3316126F, 0F, 0F);
	      HelmRidgeCenter6 = new ModelRenderer(this, 32, 0);
	      HelmRidgeCenter6.addBox(-0.499F, -14.2F, -1F, 1, 6, 2, expand/3);
	      HelmRidgeCenter6.setRotationPoint(0F, 0F, 0F);
	      HelmRidgeCenter6.setTextureSize(64, 32);
	      HelmRidgeCenter6.mirror = true;
	      setRotation(HelmRidgeCenter6, -0.3665191F, 0F, 0F);
	      HelmRidgeCenter7 = new ModelRenderer(this, 32, 0);
	      HelmRidgeCenter7.addBox(-0.501F, -14.2F, -1F, 1, 6, 2, expand/3);
	      HelmRidgeCenter7.setRotationPoint(0F, 0F, 0F);
	      HelmRidgeCenter7.setTextureSize(64, 32);
	      HelmRidgeCenter7.mirror = true;
	      setRotation(HelmRidgeCenter7, 0.1919862F, 0F, 0F);
	      HelmRidgeCenter8 = new ModelRenderer(this, 32, 0);
	      HelmRidgeCenter8.addBox(-0.499F, -14.2F, -1F, 1, 6, 2, expand/3);
	      HelmRidgeCenter8.setRotationPoint(0F, 0F, 0F);
	      HelmRidgeCenter8.setTextureSize(64, 32);
	      HelmRidgeCenter8.mirror = true;
	      setRotation(HelmRidgeCenter8, -0.2268928F, 0F, 0F);
	      HelmRidgeCenter9 = new ModelRenderer(this, 32, 0);
	      HelmRidgeCenter9.addBox(-0.501F, -12.5F, -1F, 1, 4, 2, expand/3);
	      HelmRidgeCenter9.setRotationPoint(0F, 0F, 0F);
	      HelmRidgeCenter9.setTextureSize(64, 32);
	      HelmRidgeCenter9.mirror = true;
	      setRotation(HelmRidgeCenter9, 0F, 0F, 0F);
	      HelmRidgePlateBack = new ModelRenderer(this, 60, 12);
	      HelmRidgePlateBack.addBox(-1F, -9.2F, 1F, 2, 1, 3, expand/3);
	      HelmRidgePlateBack.setRotationPoint(0F, 0F, 0F);
	      HelmRidgePlateBack.setTextureSize(64, 32);
	      HelmRidgePlateBack.mirror = true;
	      setRotation(HelmRidgePlateBack, -0.1570796F, 0F, 0F);
	      HelmRidgePlateCenter = new ModelRenderer(this, 58, 10);
	      HelmRidgePlateCenter.addBox(-1F, -8.9F, -2.4F, 2, 1, 5, expand/3);
	      HelmRidgePlateCenter.setRotationPoint(0F, 0F, 0F);
	      HelmRidgePlateCenter.setTextureSize(64, 32);
	      HelmRidgePlateCenter.mirror = true;
	      setRotation(HelmRidgePlateCenter, 0F, 0F, 0F);
	      HelmRidgePlateFront = new ModelRenderer(this, 60, 12);
	      HelmRidgePlateFront.addBox(-1F, -9.2F, -4F, 2, 1, 3, expand/3);
	      HelmRidgePlateFront.setRotationPoint(0F, 0F, 0F);
	      HelmRidgePlateFront.setTextureSize(64, 32);
	      HelmRidgePlateFront.mirror = true;
	      setRotation(HelmRidgePlateFront, 0.1570796F, 0F, 0F);
	      LeftHelmTop = new ModelRenderer(this, 80, 0);
	      LeftHelmTop.addBox(-0.5666667F, -8.5F, -4.501F, 4, 1, 9, expand/3);
	      LeftHelmTop.setRotationPoint(0F, 0F, 0F);
	      LeftHelmTop.setTextureSize(64, 32);
	      LeftHelmTop.mirror = true;
	      setRotation(LeftHelmTop, 0F, 0F, 0.122173F);
	      RightHelmTop = new ModelRenderer(this, 80, 0);
	      RightHelmTop.addBox(-3.566667F, -8.5F, -4.501F, 4, 1, 9, expand/3);
	      RightHelmTop.setRotationPoint(0F, 0F, 0F);
	      RightHelmTop.setTextureSize(64, 32);
	      RightHelmTop.mirror = true;
	      setRotation(RightHelmTop, 0F, 0F, -0.1047198F);
	      HelmBackPlate = new ModelRenderer(this, 60, 0);
	      HelmBackPlate.addBox(-3.5F, -8F, 3.502F, 7, 8, 1, expand/3);
	      HelmBackPlate.setRotationPoint(0F, 0F, 0F);
	      HelmBackPlate.setTextureSize(64, 32);
	      HelmBackPlate.mirror = true;
	      setRotation(HelmBackPlate, 0F, 0F, 0F);
	      LeftHelmForeheadPlate = new ModelRenderer(this, 52, 0);
	      LeftHelmForeheadPlate.addBox(3.5F, -8F, -4.5F, 1, 3, 3, expand/3);
	      LeftHelmForeheadPlate.setRotationPoint(0F, 0F, 0F);
	      LeftHelmForeheadPlate.setTextureSize(64, 32);
	      LeftHelmForeheadPlate.mirror = true;
	      setRotation(LeftHelmForeheadPlate, 0F, 0F, 0F);
	      LeftHelmSidePlate = new ModelRenderer(this, 38, 0);
	      LeftHelmSidePlate.addBox(3.5F, -8F, -1.5F, 1, 8, 6, expand/3);
	      LeftHelmSidePlate.setRotationPoint(0F, 0F, 0F);
	      LeftHelmSidePlate.setTextureSize(64, 32);
	      LeftHelmSidePlate.mirror = true;
	      setRotation(LeftHelmSidePlate, 0F, 0F, 0F);
	      RightHelmForeheadPlate = new ModelRenderer(this, 52, 0);
	      RightHelmForeheadPlate.addBox(-4.5F, -8F, -4.5F, 1, 3, 3, expand/3);
	      RightHelmForeheadPlate.setRotationPoint(0F, 0F, 0F);
	      RightHelmForeheadPlate.setTextureSize(64, 32);
	      RightHelmForeheadPlate.mirror = true;
	      setRotation(RightHelmForeheadPlate, 0F, 0F, 0F);
	      RightHelmSidePlate = new ModelRenderer(this, 38, 0);
	      RightHelmSidePlate.addBox(-4.5F, -8F, -1.5F, 1, 8, 6, expand/3);
	      RightHelmSidePlate.setRotationPoint(0F, 0F, 0F);
	      RightHelmSidePlate.setTextureSize(64, 32);
	      RightHelmSidePlate.mirror = true;
	      setRotation(RightHelmSidePlate, 0F, 0F, 0F);
	      RightHelmSideFacePlate = new ModelRenderer(this, 67, 17);
	      RightHelmSideFacePlate.addBox(-4.5F, -3F, -4.5F, 1, 3, 3, expand/3);
	      RightHelmSideFacePlate.setRotationPoint(0F, 0F, 0F);
	      RightHelmSideFacePlate.setTextureSize(64, 32);
	      RightHelmSideFacePlate.mirror = true;
	      setRotation(RightHelmSideFacePlate, 0F, 0F, 0F);
	      RightHelmFacePlate = new ModelRenderer(this, 60, 17);
	      RightHelmFacePlate.addBox(-4.166667F, -3F, -4.8F, 2, 3, 1, expand/3);
	      RightHelmFacePlate.setRotationPoint(0F, 0F, 0F);
	      RightHelmFacePlate.setTextureSize(64, 32);
	      RightHelmFacePlate.mirror = true;
	      setRotation(RightHelmFacePlate, 0F, 0.0698132F, 0F);
	      LeftHelmSideFacePlate = new ModelRenderer(this, 67, 17);
	      LeftHelmSideFacePlate.addBox(3.5F, -3F, -4.5F, 1, 3, 3, expand/3);
	      LeftHelmSideFacePlate.setRotationPoint(0F, 0F, 0F);
	      LeftHelmSideFacePlate.setTextureSize(64, 32);
	      LeftHelmSideFacePlate.mirror = true;
	      setRotation(LeftHelmSideFacePlate, 0F, 0F, 0F);
	      LeftHelmFacePlate = new ModelRenderer(this, 60, 17);
	      LeftHelmFacePlate.addBox(2.1F, -3F, -4.8F, 2, 3, 1, expand/3);
	      LeftHelmFacePlate.setRotationPoint(0F, 0F, 0F);
	      LeftHelmFacePlate.setTextureSize(64, 32);
	      LeftHelmFacePlate.mirror = true;
	      setRotation(LeftHelmFacePlate, 0F, -0.0698132F, 0F);
	      
	      //Body
	      body = new ModelRenderer(this, 102, 13);
	      body.addBox(-4F, 0F, -2F, 8, 12, 4, expand/3);
	      body.setRotationPoint(0F, 0F, 0F);
	      body.setTextureSize(64, 32);
	      body.mirror = true;
	      setRotation(body, 0F, 0F, 0F);
	      ChestPlate = new ModelRenderer(this, 20, 32);
	      ChestPlate.addBox(-4.5F, 0.5F, -3F, 4, 4, 1, expand/3);
	      ChestPlate.setRotationPoint(0F, 0F, 0F);
	      ChestPlate.setTextureSize(64, 32);
	      ChestPlate.mirror = true;
	      setRotation(ChestPlate, -0.0698132F, 0F, 0F);
	      ChestPlate2 = new ModelRenderer(this, 20, 37);
	      ChestPlate2.addBox(-4F, 1F, -2.7F, 8, 4, 1, expand/3);
	      ChestPlate2.setRotationPoint(0F, 0F, 0F);
	      ChestPlate2.setTextureSize(64, 32);
	      ChestPlate2.mirror = true;
	      setRotation(ChestPlate2, 0.0349066F, 0F, 0F);
	      ChestPlate3 = new ModelRenderer(this, 20, 32);
	      ChestPlate3.addBox(0.5F, 0.5F, -3F, 4, 4, 1, expand/3);
	      ChestPlate3.setRotationPoint(0F, 0F, 0F);
	      ChestPlate3.setTextureSize(64, 32);
	      ChestPlate3.mirror = true;
	      setRotation(ChestPlate3, -0.0698132F, 0F, 0F);
	      ChestPlate4 = new ModelRenderer(this, 20, 42);
	      ChestPlate4.addBox(-3.5F, 4.5F, -2.3F, 7, 2, 1, expand/3);
	      ChestPlate4.setRotationPoint(0F, 0F, 0F);
	      ChestPlate4.setTextureSize(64, 32);
	      ChestPlate4.mirror = true;
	      setRotation(ChestPlate4, 0F, 0F, 0F);
	      Girdle = new ModelRenderer(this, 20, 56);
	      Girdle.addBox(-4.5F, 8.5F, -2.5F, 9, 3, 5, expand/3);
	      Girdle.setRotationPoint(0F, 0F, 0F);
	      Girdle.setTextureSize(64, 32);
	      Girdle.mirror = true;
	      setRotation(Girdle, 0F, 0F, 0F);
	      BackPlate3 = new ModelRenderer(this, 48, 57);
	      BackPlate3.addBox(-4F, 0F, 1.5F, 8, 4, 1, expand/3);
	      BackPlate3.setRotationPoint(0F, 0F, 0F);
	      BackPlate3.setTextureSize(64, 32);
	      BackPlate3.mirror = true;
	      setRotation(BackPlate3, 0F, 0F, 0F);
	      Cloak = new ModelRenderer(this, 81, 15);
	      Cloak.addBox(-4F, 0F, 2.5F, 8, 20, 0, expand/3);
	      Cloak.setRotationPoint(0F, 0F, 0F);
	      Cloak.setTextureSize(64, 32);
	      Cloak.mirror = true;
	      setRotation(Cloak, 0.0274533F, 0F, 0F);
	      Buckle = new ModelRenderer(this, 9, 57);
	      Buckle.addBox(-2F, 8F, -2.6F, 4, 4, 1, expand/3);
	      Buckle.setRotationPoint(0F, 0F, 0F);
	      Buckle.setTextureSize(64, 32);
	      Buckle.mirror = true;
	      setRotation(Buckle, 0F, 0F, 0F);
	      
	      //Arms
	      rightarm = new ModelRenderer(this, 104, 30);
	      rightarm.addBox(-3F, -2F, -2F, 4, 12, 4, expand/3);
	      rightarm.setRotationPoint(0F, 0F, 0F);
	      rightarm.setTextureSize(64, 32);
	      rightarm.mirror = true;
	      setRotation(rightarm, 0F, 0F, 0F);
	      RightShoulderBase = new ModelRenderer(this, 40, 46);
	      RightShoulderBase.addBox(-3.5F, -2.502F, -2.5F, 5, 5, 5, expand/3);
	      RightShoulderBase.setRotationPoint(0F, 0F, 0F);
	      RightShoulderBase.setTextureSize(64, 32);
	      RightShoulderBase.mirror = true;
	      setRotation(RightShoulderBase, 0F, 0F, -0.0523599F);
	      RightShoulderPlate = new ModelRenderer(this, 44, 36);
	      RightShoulderPlate.addBox(-4.2F, -1.4F, -3.5F, 1, 3, 7, expand/3);
	      RightShoulderPlate.setRotationPoint(0F, 0F, 0F);
	      RightShoulderPlate.setTextureSize(64, 32);
	      RightShoulderPlate.mirror = true;
	      setRotation(RightShoulderPlate, 0F, 0F, 0.2792527F);
	      LeftShoulderTopPlate = new ModelRenderer(this, 44, 36);
	      LeftShoulderTopPlate.addBox(3.15F, 0.6F, -3.501F, 1, 3, 7, expand/3);
	      LeftShoulderTopPlate.setRotationPoint(0F, 0F, 0F);
	      LeftShoulderTopPlate.setTextureSize(64, 32);
	      LeftShoulderTopPlate.mirror = true;
	      setRotation(LeftShoulderTopPlate, 0F, 0F, -0.9599311F);
	      leftarm = new ModelRenderer(this, 104, 30);
	      leftarm.addBox(-1F, -2F, -2.001F, 4, 12, 4, expand/3);
	      leftarm.setRotationPoint(0F, 0F, 0F);
	      leftarm.setTextureSize(64, 32);
	      leftarm.mirror = true;
	      setRotation(leftarm, 0F, 0F, 0F);
	      LeftShoulderBase = new ModelRenderer(this, 40, 46);
	      LeftShoulderBase.addBox(-1.5F, -2.502F, -2.5F, 5, 5, 5, expand/3);
	      LeftShoulderBase.setRotationPoint(0F, 0F, 0F);
	      LeftShoulderBase.setTextureSize(64, 32);
	      LeftShoulderBase.mirror = true;
	      setRotation(LeftShoulderBase, 0F, 0F, 0.0523599F);
	      RightShoulderBase2 = new ModelRenderer(this, 19, 46);
	      RightShoulderBase2.addBox(-3.5F, -2.5F, -3F, 4, 4, 6, expand/3);
	      RightShoulderBase2.setRotationPoint(0F, 0F, 0F);
	      RightShoulderBase2.setTextureSize(64, 32);
	      RightShoulderBase2.mirror = true;
	      setRotation(RightShoulderBase2, 0F, 0F, 0.0698132F);
	      LeftShoulderBase2 = new ModelRenderer(this, 19, 46);
	      LeftShoulderBase2.addBox(-0.5F, -2.5F, -3F, 4, 4, 6, expand/3);
	      LeftShoulderBase2.setRotationPoint(0F, 0F, 0F);
	      LeftShoulderBase2.setTextureSize(64, 32);
	      LeftShoulderBase2.mirror = true;
	      setRotation(LeftShoulderBase2, 0F, 0F, -0.0523599F);
	      RightBottomShoulderPlate = new ModelRenderer(this, 86, 38);
	      RightBottomShoulderPlate.addBox(-3.7F, 1.1F, -2.999F, 1, 3, 6, expand/3);
	      RightBottomShoulderPlate.setRotationPoint(0F, 0F, 0F);
	      RightBottomShoulderPlate.setTextureSize(64, 32);
	      RightBottomShoulderPlate.mirror = true;
	      setRotation(RightBottomShoulderPlate, 0F, 0F, 0.2792527F);
	      LeftBottomShoulderPlate = new ModelRenderer(this, 86, 38);
	      LeftBottomShoulderPlate.addBox(2.7F, 1.1F, -2.999F, 1, 3, 6, expand/3);
	      LeftBottomShoulderPlate.setRotationPoint(0F, 0F, 0F);
	      LeftBottomShoulderPlate.setTextureSize(64, 32);
	      LeftBottomShoulderPlate.mirror = true;
	      setRotation(LeftBottomShoulderPlate, 0F, 0F, -0.2792527F);
	      LeftShoulderPlate = new ModelRenderer(this, 44, 36);
	      LeftShoulderPlate.addBox(3.1F, -1.4F, -3.5F, 1, 3, 7, expand/3);
	      LeftShoulderPlate.setRotationPoint(0F, 0F, 0F);
	      LeftShoulderPlate.setTextureSize(64, 32);
	      LeftShoulderPlate.mirror = true;
	      setRotation(LeftShoulderPlate, 0F, 0F, -0.2792527F);
	      LeftShoulderMainPlate = new ModelRenderer(this, 61, 38);
	      LeftShoulderMainPlate.addBox(0.15F, -2.8F, -3.5F, 5, 1, 7, expand/3);
	      LeftShoulderMainPlate.setRotationPoint(0F, 0F, 0F);
	      LeftShoulderMainPlate.setTextureSize(64, 32);
	      LeftShoulderMainPlate.mirror = true;
	      setRotation(LeftShoulderMainPlate, 0F, 0F, -0.1396263F);
	      RightShoulderTopPlate = new ModelRenderer(this, 44, 36);
	      RightShoulderTopPlate.addBox(-4.2F, 0.6F, -3.5F, 1, 3, 7, expand/3);
	      RightShoulderTopPlate.setRotationPoint(0F, 0F, 0F);
	      RightShoulderTopPlate.setTextureSize(64, 32);
	      RightShoulderTopPlate.mirror = true;
	      setRotation(RightShoulderTopPlate, 0F, 0F, 0.9599311F);
	      RightShoulderMainPlate = new ModelRenderer(this, 61, 38);
	      RightShoulderMainPlate.addBox(-5.2F, -2.8F, -3.5F, 5, 1, 7, expand/3);
	      RightShoulderMainPlate.setRotationPoint(0F, 0F, 0F);
	      RightShoulderMainPlate.setTextureSize(64, 32);
	      RightShoulderMainPlate.mirror = true;
	      setRotation(RightShoulderMainPlate, 0F, 0F, 0.1396263F);
	      RightShoulderDeco = new ModelRenderer(this, 61, 47);
	      RightShoulderDeco.addBox(-2.5F, -0.5F, -3.503F, 2, 2, 7, expand/3);
	      RightShoulderDeco.setRotationPoint(0F, 0F, 0F);
	      RightShoulderDeco.setTextureSize(64, 32);
	      RightShoulderDeco.mirror = true;
	      setRotation(RightShoulderDeco, 0F, 0F, 0.7853982F);
	      LeftShoulderDeco = new ModelRenderer(this, 61, 47);
	      LeftShoulderDeco.addBox(-0.5F, -2.5F, -3.503F, 2, 2, 7, expand/3);
	      LeftShoulderDeco.setRotationPoint(0F, 0F, 0F);
	      LeftShoulderDeco.setTextureSize(64, 32);
	      LeftShoulderDeco.mirror = true;
	      setRotation(LeftShoulderDeco, 0F, 0F, 0.7853982F);
	      
	      //Legs
	      leftleg = new ModelRenderer(this, 107, 0);
	      leftleg.addBox(-2F, 0F, -2F, 4, 12, 4, expand/3);
	      leftleg.setRotationPoint(0F, 0F, 0F);
	      leftleg.setTextureSize(64, 32);
	      leftleg.mirror = true;
	      setRotation(leftleg, 0F, 0F, 0F);
	      rightleg = new ModelRenderer(this, 107, 0);
	      rightleg.addBox(-2F, 0F, -2F, 4, 12, 4, expand/3);
	      rightleg.setRotationPoint(0F, 0F, 0F);
	      rightleg.setTextureSize(64, 32);
	      rightleg.mirror = true;
	      setRotation(rightleg, 0F, 0F, 0F);
	      LeftThighPlate = new ModelRenderer(this, 0, 38);
	      LeftThighPlate.addBox(-1F, 3F, -2.3F, 2, 1, 1, expand/3);
	      LeftThighPlate.setRotationPoint(0F, 0F, 0F);
	      LeftThighPlate.setTextureSize(64, 32);
	      LeftThighPlate.mirror = true;
	      setRotation(LeftThighPlate, 0F, 0F, 0F);
	      LeftThighPlate2 = new ModelRenderer(this, 0, 33);
	      LeftThighPlate2.addBox(-1.5F, 0F, -2.5F, 3, 3, 1, expand/3);
	      LeftThighPlate2.setRotationPoint(0F, 0F, 0F);
	      LeftThighPlate2.setTextureSize(64, 32);
	      LeftThighPlate2.mirror = true;
	      setRotation(LeftThighPlate2, 0F, 0F, 0F);
	      RightThighPlate = new ModelRenderer(this, 0, 33);
	      RightThighPlate.addBox(-1.5F, 0F, -2.5F, 3, 3, 1, expand/3);
	      RightThighPlate.setRotationPoint(0F, 0F, 0F);
	      RightThighPlate.setTextureSize(64, 32);
	      RightThighPlate.mirror = true;
	      setRotation(RightThighPlate, 0F, 0F, 0F);
	      RightThighPlate2 = new ModelRenderer(this, 0, 38);
	      RightThighPlate2.addBox(-1F, 3F, -2.3F, 2, 1, 1, expand/3);
	      RightThighPlate2.setRotationPoint(0F, 0F, 0F);
	      RightThighPlate2.setTextureSize(64, 32);
	      RightThighPlate2.mirror = true;
	      setRotation(RightThighPlate2, 0F, 0F, 0F);
	      RightThighPlate3 = new ModelRenderer(this, 0, 41);
	      RightThighPlate3.addBox(-1F, 5.5F, -2.5F, 2, 2, 1, expand/3);
	      RightThighPlate3.setRotationPoint(0F, 0F, 0F);
	      RightThighPlate3.setTextureSize(64, 32);
	      RightThighPlate3.mirror = true;
	      setRotation(RightThighPlate3, 0F, 0F, 0F);
	      LeftThighPlate3 = new ModelRenderer(this, 0, 41);
	      LeftThighPlate3.addBox(-1F, 5.5F, -2.5F, 2, 2, 1, expand/3);
	      LeftThighPlate3.setRotationPoint(0F, 0F, 0F);
	      LeftThighPlate3.setTextureSize(64, 32);
	      LeftThighPlate3.mirror = true;
	      
	      setRotation(LeftThighPlate3, 0F, 0F, 0F);
	      RightBoot = new ModelRenderer(this, 80, 34);
	      RightBoot.addBox(-2.5F, 8F, -2.5F, 5, 4, 5, expand/3);
	      RightBoot.setRotationPoint(0F, 0F, 0F);
	      RightBoot.setTextureSize(128, 64);
	      RightBoot.mirror = true;
	      setRotation(RightBoot, 0F, 0F, 0F);
	      
	      LeftBoot = new ModelRenderer(this, 80, 34);
	      LeftBoot.addBox(-2.5F, 8F, -2.5F, 5, 4, 5, expand/3);
	      LeftBoot.setRotationPoint(0F, 0F, 0F);
	      LeftBoot.setTextureSize(128, 64);
	      LeftBoot.mirror = true;
	      setRotation(LeftBoot, 0F, 0F, 0F);
	      
	      this.bipedHead.addChild(head);
	      this.bipedHead.addChild(HelmForeHead);
	      this.bipedHead.addChild(LeftHelmForeHead);
	      this.bipedHead.addChild(RightHelmForeHead);
	      this.bipedHead.addChild(HelmNosePlate);
	      this.bipedHead.addChild(HelmRidgeCenter);
	      this.bipedHead.addChild(HelmRidgeCenter2);
	      this.bipedHead.addChild(HelmRidgeCenter3);
	      this.bipedHead.addChild(HelmRidgeCenter4);
	      this.bipedHead.addChild(HelmRidgeCenter5);
	      this.bipedHead.addChild(HelmRidgeCenter6);
	      this.bipedHead.addChild(HelmRidgeCenter7);
	      this.bipedHead.addChild(HelmRidgeCenter8);
	      this.bipedHead.addChild(HelmRidgeCenter9);
	      this.bipedHead.addChild(HelmRidgePlateBack);
	      this.bipedHead.addChild(HelmRidgePlateCenter);
	      this.bipedHead.addChild(HelmRidgePlateFront);
	      this.bipedHead.addChild(LeftHelmTop);
	      this.bipedHead.addChild(RightHelmTop);
	      this.bipedHead.addChild(HelmBackPlate);
	      this.bipedHead.addChild(LeftHelmForeheadPlate);
	      this.bipedHead.addChild(LeftHelmSidePlate);
	      this.bipedHead.addChild(RightHelmForeheadPlate);
	      this.bipedHead.addChild(RightHelmSidePlate);
	      this.bipedHead.addChild(RightHelmSideFacePlate);
	      this.bipedHead.addChild(RightHelmFacePlate);
	      this.bipedHead.addChild(LeftHelmSideFacePlate);
	      this.bipedHead.addChild(LeftHelmFacePlate);
	      
	      body.addChild(ChestPlate);
	      body.addChild(ChestPlate2);
	      body.addChild(ChestPlate3);
	      body.addChild(ChestPlate4);
	      this.bipedBody.addChild(body);
	      this.bipedBody.addChild(Girdle);
	      this.bipedBody.addChild(Buckle);
	      this.bipedBody.addChild(BackPlate3);
	      
	      this.bipedLeftArm.addChild(leftarm);
	      this.bipedLeftArm.addChild(LeftShoulderPlate);
	      this.bipedLeftArm.addChild(LeftShoulderBase);
	      this.bipedLeftArm.addChild(LeftShoulderBase2);
	      this.bipedLeftArm.addChild(LeftShoulderTopPlate);
	      this.bipedLeftArm.addChild(LeftBottomShoulderPlate);
	      this.bipedLeftArm.addChild(LeftShoulderMainPlate);
	      this.bipedLeftArm.addChild(LeftShoulderDeco);
	      
	      this.bipedRightArm.addChild(rightarm);
	      this.bipedRightArm.addChild(RightShoulderBase);
	      this.bipedRightArm.addChild(RightShoulderMainPlate);
	      this.bipedRightArm.addChild(RightShoulderPlate);
	      this.bipedRightArm.addChild(RightShoulderTopPlate);
	      this.bipedRightArm.addChild(RightBottomShoulderPlate);
	      this.bipedRightArm.addChild(RightShoulderBase2);
	      this.bipedRightArm.addChild(RightShoulderDeco);
	      
	      
	      this.bipedLeftLeg.addChild(leftleg);
	      this.bipedLeftLeg.addChild(LeftThighPlate);
	      this.bipedLeftLeg.addChild(LeftThighPlate2);
	      this.bipedLeftLeg.addChild(LeftThighPlate3);
	      this.bipedLeftLeg.addChild(LeftBoot);
	      
	      this.bipedRightLeg.addChild(rightleg);
	      this.bipedRightLeg.addChild(RightThighPlate);
	      this.bipedRightLeg.addChild(RightThighPlate2);
	      this.bipedRightLeg.addChild(RightThighPlate3);
	      this.bipedRightLeg.addChild(RightBoot);
	      
	      this.bipedCloak.addChild(Cloak);
	  }
	  
	  public void rotateCloak(float rot){
		  setRotation(Cloak, rot, 0F, 0F);
	  }
	  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
	  {
	    super.render(entity, f, f1, f2, f3, f4, f5);
	    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	   
	  }
	  
	  private void setRotation(ModelRenderer model, float x, float y, float z)
	  {
	    model.rotateAngleX = x;
	    model.rotateAngleY = y;
	    model.rotateAngleZ = z;
	  }

}
